version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notifications
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data