// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
	"time"
)

type Notification struct {
	ID          string
	RecipientID string
	Body        string
	Title       string
	CreatedAt   time.Time
	ReadAt      sql.NullTime
	DeletedAt   sql.NullTime
}
